### ISSUE TITLE
你好，我想问一下可以在哪里运行呢？我发现在电脑上运行会报错

### ISSUE THREAD

**Issue by HLLF-FAN** [RainYangty/UDTW#1]

**Comment by RainYangty** [comment]
在Windows下装好依赖后就可以用Python运行main.py，如果是103行报错，是由于API更新但这边更新不及时导致，抱歉

**Comment by RainYangty** [comment]
现已解决，可以下载最新版本

**Comment by HLLF-FAN** [comment]
> 在Windows下装好依赖后就可以用Python运行main.py，如果是103行报错，是由于API更新但这边更新不及时导致，抱歉

不是103行报错呢？

**Comment by RainYangty** [comment]
错误信息是什么

**Comment by HLLF-FAN** [comment]
pygame 2.5.2 (SDL 2.28.3, Python 3.10.11)
Hello from the pygame community. https://www.pygame.org/contribute.html
Exception in thread Thread-2 (sc_eew):
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "c:\Users\23665\Desktop\UDTW-main\main.py", line 148, in sc_eew
    playsound(path + r"\audio/update.mp3")
  File "c:\Users\23665\Desktop\UDTW-main\main.py", line 25, in playsound
Exception in thread Thread-1 (cenc):
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\threading.py", line 1016, in _bootstrap_inner
    pygame.mixer.music.load(file)
pygame.error: No such file or directory: 'C:\Users\23665\audio/update.mp3'.
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "c:\Users\23665\Desktop\UDTW-main\main.py", line 99, in cenc
    playsound(path + r"\audio/cenc.mp3")
  File "c:\Users\23665\Desktop\UDTW-main\main.py", line 25, in playsound
    pygame.mixer.music.load(file)
pygame.error: No such file or directory: 'C:\Users\23665\audio/cenc.mp3'.

**Comment by RainYangty** [comment]
现已解决

**Comment by HLLF-FAN** [comment]
现在推送没问题了，但是
![image](https://github.com/RainYangty/UDTW/assets/107034178/0f9205eb-66a2-4355-bbb2-0903e3319923)
会报错

**Comment by RainYangty** [comment]
请检查您那边的网络是否畅通，我这边近期将更新拉取逻辑，会降低触发概率

**Comment by HLLF-FAN** [comment]
好的，感谢大佬

**Comment by HLLF-FAN** [comment]
https://apidoc.fan0225.top:60225/web/#/687152616/284756541我这里有几个api不知道用得上不？

**Comment by RainYangty** [comment]
万分感谢
